ipa_domain: sandbox1108.opentlc.com
ipa_realm: SANDBOX1108.OPENTLC.COM
ipa_server: "{{ hostvars[groups['idm'][0]].inventory_hostname }}"
ipa_admin_user: admin
vault_idm_admin_password: red22hat

aws_region: us-east-2

stig_ami_id: ami-0dee8d0e6a88728d8
standard_ami_id: ami-0672bca11b972c7d0

keycloak_realm: CORP-REALM
keycloak_base_url: "http://{{ hostvars[groups['keycloak'][0]].inventory_hostname }}:8080"

openscap_report_dir: /tmp/openscap-reports

