---
- name: Configure IdM server
  hosts: idm
  become: true
  gather_facts: false

  tasks:
    - name: Debug IdM variables
      debug:
        msg:
          - "IPA Realm: {{ ipa_realm }}"
          - "IPA Domain: {{ ipa_domain }}"
          - "IPA Server: {{ ipa_server }}"
          - "IPA Admin Password: {{ vault_idm_admin_password }}"

    - name: Install IdM server with integrated DNS
      command: >
        ipa-server-install --unattended
        --realm {{ ipa_realm }}
        --domain {{ ipa_domain }}
        --ds-password {{ vault_idm_admin_password }}
        --admin-password {{ vault_idm_admin_password }}
        --setup-dns --no-forwarders
      args:
        creates: /etc/ipa/default.conf

