---
- name: Configure IdM server and populate dummy users
  hosts: tag_idm
  become: true
  vars:
    ipa_domain: sandbox1108.opentlc.com
    ipa_realm: SANDBOX1108.OPENTLC.COM
    ipa_admin_user: admin
    ipa_admin_password: red22hat
    dummy_users:
      - { username: lmorales, first: Leo,      last: Morales }
      - { username: qscott,   first: Quinn,    last: Scott }
      - { username: adiaz,    first: Andrew,   last: Diaz }
      - { username: nchavez,  first: Nolan,    last: Chavez }
      - { username: gtorres,  first: Gianna,   last: Torres }
      - { username: sjackson, first: Serenity, last: Jackson }
      - { username: lreyes,   first: Lucas,    last: Reyes }
      - { username: mlopez,   first: Muhammad, last: Lopez }

  tasks:
    - name: Wait for SSH to become available
      wait_for:
        port: 22
        delay: 5
        timeout: 300

    - name: Set ipa_server fact dynamically
      set_fact:
        ipa_server: "{{ ansible_host }}"

    - name: Install IdM server packages
      dnf:
        name: ipa-server
        state: present
        update_cache: true

    - name: Install IdM server with integrated DNS and external forwarders
      command: >
        ipa-server-install --unattended
        --realm {{ ipa_realm }}
        --domain {{ ipa_domain }}
        --ds-password {{ ipa_admin_password }}
        --admin-password {{ ipa_admin_password }}
        --setup-dns
        --forwarder=8.8.8.8
        --forwarder=4.2.2.1
      args:
        creates: /etc/ipa/default.conf

    - name: Wait for IdM API to become available
      uri:
        url: "https://{{ ipa_server }}/ipa/session/login_password"
        method: POST
        status_code: 200
        validate_certs: no
      register: result
      until: result.status == 200
      retries: 15
      delay: 10

    - name: Ensure Kerberos credentials for IPA admin
      shell: |
        echo '{{ ipa_admin_password }}' | kinit {{ ipa_admin_user }}@{{ ipa_realm }}
      environment:
        KRB5_CONFIG: /etc/krb5.conf

    - name: Create dummy IdM users
      loop: "{{ dummy_users }}"
      loop_control:
        label: "{{ item.username }}"
      command: >
        ipa user-add {{ item.username }}
        --first={{ item.first }}
        --last={{ item.last }}
        --homedir=/home/{{ item.username }}
        --shell=/bin/bash
      register: ipa_user_create
      failed_when: ipa_user_create.rc != 0 and 'already exists' not in ipa_user_create.stderr

    - name: Set password for dummy users
      loop: "{{ dummy_users }}"
      loop_control:
        label: "{{ item.username }}"
      shell: |
        echo 'red22hat' | ipa passwd {{ item.username }}
      register: ipa_passwd
      failed_when: ipa_passwd.rc != 0 and 'Password change failed' in ipa_passwd.stderr

    - name: Set password expiration far in the future
      loop: "{{ dummy_users }}"
      loop_control:
        label: "{{ item.username }}"
      command: >
        ipa user-mod {{ item.username }} --setattr=krbPasswordExpiration=20301231011529

