---
- name: Configure IdM server and populate dummy users
  hosts: tag_idm
  become: true
  vars:
    ipa_realm: "{{ ipa_realm }}"
    ipa_domain: "{{ ipa_domain }}"
    ipa_admin_user: "{{ ipa_admin_user }}"
    ipa_admin_password: "{{ vault_idm_admin_password }}"
  tasks:
    - name: Install IdM server packages
      package:
        name:
          - ipa-server
          - ipa-server-dns
        state: present

    - name: Install IdM server with integrated DNS
      command: >
        ipa-server-install --unattended
        --realm {{ ipa_realm }}
        --domain {{ ipa_domain }}
        --ds-password {{ ipa_admin_password }}
        --admin-password {{ ipa_admin_password }}
        --setup-dns --no-forwarders
      args:
        creates: /etc/ipa/default.conf

    - name: Ensure Kerberos credentials for IPA admin
      command: echo "{{ ipa_admin_password }}" | kinit {{ ipa_admin_user }}@{{ ipa_realm }}
      register: kinit_result
      changed_when: false

    - name: Add dummy users
      loop:
        - { username: "lmorales", first: "Leo", last: "Morales" }
        - { username: "qscott", first: "Quinn", last: "Scott" }
        - { username: "adiaz", first: "Andrew", last: "Diaz" }
        - { username: "nchavez", first: "Nolan", last: "Chavez" }
        - { username: "gtorres", first: "Gianna", last: "Torres" }
        - { username: "sjackson", first: "Serenity", last: "Jackson" }
        - { username: "lreyes", first: "Lucas", last: "Reyes" }
        - { username: "mlopez", first: "Muhammad", last: "Lopez" }
      command: >
        ipa user-add {{ item.username }} --first {{ item.first }} --last {{ item.last }} \
        --homedir=/home/{{ item.username }} --shell=/bin/bash
      ignore_errors: yes

    - name: Set user passwords
      loop:
        - lmorales
        - qscott
        - adiaz
        - nchavez
        - gtorres
        - sjackson
        - lreyes
        - mlopez
      shell: echo -e "red22hat\nred22hat" | ipa passwd {{ item }}

    - name: Set password expiration far in the future
      loop:
        - lmorales
        - qscott
        - adiaz
        - nchavez
        - gtorres
        - sjackson
        - lreyes
        - mlopez
      command: ipa user-mod {{ item }} --setattr=krbPasswordExpiration=20301231011529
