---
- name: Configure IdM server and populate dummy users
  hosts: tag_idm
  become: true
  tasks:
    - name: Set ipa_server fact dynamically
      set_fact:
        ipa_server: "{{ hostvars[inventory_hostname].ansible_host }}"

    - name: Install IdM server packages
      dnf:
        name:
          - ipa-server
          - ipa-server-dns
        state: present

    - name: Install IdM server with integrated DNS
      command: >
        ipa-server-install --unattended
        --realm {{ ipa_realm }}
        --domain {{ ipa_domain }}
        --ds-password {{ vault_idm_admin_password }}
        --admin-password {{ vault_idm_admin_password }}
        --setup-dns --no-forwarders
      args:
        creates: /etc/ipa/default.conf

    - name: Ensure Kerberos credentials for IPA admin
      shell: echo "{{ vault_idm_admin_password }}" | kinit {{ ipa_admin_user }}@{{ ipa_realm }}
      register: kinit_output
      changed_when: false
      failed_when: kinit_output.rc != 0

    - name: Create dummy users in IdM
      loop:
        - { name: "lmorales", first: "Leo", last: "Morales" }
        - { name: "qscott", first: "Quinn", last: "Scott" }
        - { name: "adiaz", first: "Andrew", last: "Diaz" }
        - { name: "nchavez", first: "Nolan", last: "Chavez" }
        - { name: "gtorres", first: "Gianna", last: "Torres" }
        - { name: "sjackson", first: "Serenity", last: "Jackson" }
        - { name: "lreyes", first: "Lucas", last: "Reyes" }
        - { name: "mlopez", first: "Muhammad", last: "Lopez" }
      command: >
        ipa user-add {{ item.name }} \
        --first {{ item.first }} \
        --last {{ item.last }} \
        --homedir /home/{{ item.name }} \
        --shell /bin/bash
      ignore_errors: true

    - name: Set passwords for dummy users
      shell: echo -e "red22hat\nred22hat" | ipa passwd {{ item }}
      loop:
        - lmorales
        - qscott
        - adiaz
        - nchavez
        - gtorres
        - sjackson
        - lreyes
        - mlopez

    - name: Set password expiration far in future
      command: ipa user-mod {{ item }} --setattr=krbPasswordExpiration=20301231011529
      loop:
        - lmorales
        - qscott
        - adiaz
        - nchavez
        - gtorres
        - sjackson
        - lreyes
        - mlopez
