---
- name: Configure IdM server and populate dummy users
  hosts: all
  become: true
  vars:
    ipa_domain: sandbox1108.opentlc.com
    ipa_realm: SANDBOX1108.OPENTLC.COM
    ipa_admin_user: admin
    ipa_admin_password: red22hat
  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        timeout: 120

    - name: Install IdM server packages
      dnf:
        name: ipa-server
        state: present

    - name: Install IdM server with integrated DNS
      command: >
        ipa-server-install --unattended
        --realm {{ ipa_realm }}
        --domain {{ ipa_domain }}
        --ds-password {{ ipa_admin_password }}
        --admin-password {{ ipa_admin_password }}
        --setup-dns --no-forwarders
      args:
        creates: /etc/ipa/default.conf

    - name: Ensure Kerberos credentials for IPA admin
      shell: echo "{{ ipa_admin_password }}" | kinit {{ ipa_admin_user }}@{{ ipa_realm }}
      environment:
        KRB5_CONFIG: /etc/krb5.conf

    - name: Create dummy IdM users
      loop:
        - { username: "lmorales", first: "Leo", last: "Morales" }
        - { username: "qscott", first: "Quinn", last: "Scott" }
        - { username: "adiaz", first: "Andrew", last: "Diaz" }
        - { username: "nchavez", first: "Nolan", last: "Chavez" }
        - { username: "gtorres", first: "Gianna", last: "Torres" }
        - { username: "sjackson", first: "Serenity", last: "Jackson" }
        - { username: "lreyes", first: "Lucas", last: "Reyes" }
        - { username: "mlopez", first: "Muhammad", last: "Lopez" }
      block:
        - name: Add user
          command: >
            ipa user-add {{ item.username }}
            --first {{ item.first }}
            --last {{ item.last }}
            --homedir=/home/{{ item.username }}
            --shell=/bin/bash
          args:
            creates: "/home/{{ item.username }}"

        - name: Set initial password
          shell: echo -e "red22hat\nred22hat" | ipa passwd {{ item.username }}

        - name: Set password expiration
          command: ipa user-mod {{ item.username }} --setattr=krbPasswordExpiration=20301231011529

