---
- name: Configure IdM server and populate dummy users
  hosts: tag_idm
  become: true
  vars:
    ipa_domain: sandbox1108.opentlc.com
    ipa_realm: SANDBOX1108.OPENTLC.COM
    ipa_admin_user: admin
    vault_idm_admin_password: red22hat
  tasks:
    - name: Set ipa_server fact
      set_fact:
        ipa_server: "{{ ansible_host | default(public_ip_address) }}"

    - name: Install IdM server with integrated DNS
      command: >
        ipa-server-install --unattended
        --realm {{ ipa_realm }}
        --domain {{ ipa_domain }}
        --ds-password {{ vault_idm_admin_password }}
        --admin-password {{ vault_idm_admin_password }}
        --setup-dns --no-forwarders
      args:
        creates: /etc/ipa/default.conf

    - name: Create dummy users
      loop:
        - { name: 'lmorales', first: 'Leo',      last: 'Morales'  }
        - { name: 'qscott',   first: 'Quinn',    last: 'Scott'    }
        - { name: 'adiaz',    first: 'Andrew',   last: 'Diaz'     }
        - { name: 'nchavez',  first: 'Nolan',    last: 'Chavez'   }
        - { name: 'gtorres',  first: 'Gianna',   last: 'Torres'   }
        - { name: 'sjackson', first: 'Serenity', last: 'Jackson'  }
        - { name: 'lreyes',   first: 'Lucas',    last: 'Reyes'    }
        - { name: 'mlopez',   first: 'Muhammad', last: 'Lopez'    }
      command: >
        ipa user-add {{ item.name }}
        --first {{ item.first }}
        --last {{ item.last }}
        --homedir /home/{{ item.name }}
        --shell /bin/bash

