---
- name: Configure Keycloak to use IdM as LDAP source
  hosts: keycloak
  become: true
  vars:
    ipa_admin_password: "{{ vault_idm_admin_password }}"
  tasks:
    - name: Ensure Keycloak is reachable
      uri:
        url: "{{ keycloak_base_url }}/auth"
        method: GET
        return_content: yes
      register: keycloak_health
      retries: 5
      delay: 10
      until: keycloak_health.status == 200

    - name: Display Keycloak readiness
      debug:
        msg: "Keycloak is up and reachable at {{ keycloak_base_url }}"

