---
- name: Configure Keycloak
  hosts: keycloak
  become: true
  gather_facts: false

  tasks:
    - name: Debug Keycloak vars
      debug:
        msg:
          - "IPA Domain: {{ ipa_domain }}"
          - "IPA Realm: {{ ipa_realm }}"
          - "IPA Server: {{ ipa_server }}"
          - "IPA Admin User: {{ ipa_admin_user }}"
          - "IPA Admin Password: {{ vault_idm_admin_password }}"
          - "Keycloak Realm: {{ keycloak_realm }}"
          - "Keycloak Base URL: {{ keycloak_base_url }}"

    # Add your actual Keycloak configuration tasks here.
    - name: Placeholder - install Keycloak or configure integration
      debug:
        msg: "Keycloak configuration tasks go here."

