---
- name: Install and configure Keycloak
  hosts: tag_keycloak
  become: true
  vars:
    keycloak_realm: "{{ keycloak_realm }}"
    ipa_server: "{{ ipa_server }}"
    ipa_realm: "{{ ipa_realm }}"
    ipa_admin_user: "{{ ipa_admin_user }}"
    vault_idm_admin_password: "{{ vault_idm_admin_password }}"
  tasks:
    - name: Install Keycloak from RPM
      dnf:
        name: keycloak
        state: present

    - name: Enable and start Keycloak service
      systemd:
        name: keycloak
        enabled: true
        state: started

    - name: Wait for Keycloak to be available
      uri:
        url: "{{ keycloak_base_url }}/realms/master/.well-known/openid-configuration"
        method: GET
        return_content: yes
        status_code: 200
      register: keycloak_status
      retries: 20
      delay: 10
      until: keycloak_status.status == 200

