---
- name: Install and configure Keycloak with IdM integration
  hosts: tag_keycloak
  become: true
  vars:
    keycloak_realm: "{{ keycloak_realm }}"
    keycloak_base_url: "{{ keycloak_base_url }}"
    ipa_domain: "{{ ipa_domain }}"
    ipa_realm: "{{ ipa_realm }}"
    ipa_server: "{{ ipa_server }}"
    ipa_admin_user: "{{ ipa_admin_user }}"
    ipa_admin_password: "{{ vault_idm_admin_password }}"
  tasks:
    - name: Install Keycloak and dependencies
      package:
        name:
          - keycloak
          - java-17-openjdk
        state: present

    - name: Ensure Keycloak service is enabled and started
      service:
        name: keycloak
        enabled: yes
        state: started

    - name: Debug Keycloak variables
      debug:
        msg:
          - "Realm: {{ keycloak_realm }}"
          - "Base URL: {{ keycloak_base_url }}"
          - "IPA Domain: {{ ipa_domain }}"
          - "IPA Server: {{ ipa_server }}"
