# playbooks/99-destroy-infra.yml
---
- name: Destroy AWS infrastructure using Terraform
  hosts: localhost
  gather_facts: false
  vars:
    tf_dir: "{{ playbook_dir }}/../terraform"
  tasks:
    - name: Destroy Terraform-managed infrastructure
      community.general.terraform:
        project_path: "{{ tf_dir }}"
        state: absent
        force_init: true
        variables_file: "{{ tf_dir }}/terraform.tfvars"
