---
- name: Destroy AWS infrastructure using Terraform
  hosts: localhost
  gather_facts: false
  vars:
    tf_dir: "{{ playbook_dir }}/../terraform"
  tasks:
    - name: Terraform destroy with auto-approval
      community.general.terraform:
        project_path: "{{ tf_dir }}"
        state: absent
        force_init: true
        variables_file: "{{ tf_dir }}/terraform.tfvars"
      register: terraform_destroy

    - name: Show Terraform destroy output
      debug:
        var: terraform_destroy.stdout_lines

